field import: preserve generic info
rpau/javalang-compiler pull request #53
Opened 2017-05-01 11:47 UTC by cal101

2017-05-07 09:20 UTC, rpau commented on src/test/java/org/walkmod/javalang/compiler/SymbolVisitorAdapterTest.java
> +		//SymbolVisitorAdapterAssertions.assertTypeOfGenericConstant(cu);
Why are these lines of code commented? Could you add the appropriate assertions in each test case?

2017-05-07 09:21 UTC, rpau requested changes
Thanks for the contribution! However, some assertions on the tests make describe better which parts needs to be properly evaluated.

2017-05-07 12:12 UTC, cal101 commented on src/test/java/org/walkmod/javalang/compiler/SymbolVisitorAdapterTest.java
> +		//SymbolVisitorAdapterAssertions.assertTypeOfGenericConstant(cu);
These are the fluent assertions i wrote about via email. Useful but work in progress. Details in email.

2017-05-07 18:56 UTC, rpau commented on src/test/java/org/walkmod/javalang/compiler/SymbolVisitorAdapterTest.java
> +		//SymbolVisitorAdapterAssertions.assertTypeOfGenericConstant(cu);
👍

2017-05-19 18:32 UTC, rpau commented on src/test/java/org/walkmod/javalang/compiler/SymbolVisitorAdapterTest.java
> +		//SymbolVisitorAdapterAssertions.assertTypeOfGenericConstant(cu);
@cal101 can uncomment the code now?

2017-05-19 19:15 UTC, cal101 commented
OK, will take a look at the weekend.

2017-05-19 20:03 UTC, cal101 commented
Found some rest of energy. Should be done.

2017-05-25 08:46 UTC, cal101 commented
Fixed merge conflict. Should be ready for merge now.

2017-05-25 10:17 UTC, rpau commented on src/main/java/org/walkmod/javalang/compiler/actions/LoadStaticImportsAction.java
> +							boolean isVisible = Modifier.isPublic(modifiers)
This code follows a different format than you suggested to me. Could you format the code?

2017-05-25 10:43 UTC, cal101 commented
Sorry. Will take a look at all pull requests when I am back.

2017-05-25 10:48 UTC, cal101 commented
I see that formatting of the master is not clean, too but I also see that a reformatting changes things I intended to be left alone. 
The reformatting reduces readability of some tests.
I will take a look at the formatter config when I am back.

2017-05-26 07:53 UTC, cal101 commented
reformatted and rebased on master.
But please consider https://github.com/rpau/javalang-compiler/pull/66.

2017-05-28 11:52 UTC, cal101 commented
Rebased.

2017-06-06 06:46 UTC, cal101 commented
Rebased again.

2017-06-12 18:12 UTC, cal101 commented
Please tell if you have open issues. I consider it ready.

2017-06-12 21:20 UTC, rpau approved these changes

2017-06-12 21:20 UTC, rpau commented
Thanks @cal101

2017-06-12 21:21 UTC, merged